src/objects/Question_Group__c.object
<CustomObject>
    <label>Question Group</label>
    <nameField>
        <label>Question Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>Question_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Question Group</description>
        <label>Question Group</label>
        <referenceTo>Question_Group__c</referenceTo>
        <relationshipLabel>Question_Questionnaires</relationshipLabel>
        <relationshipName>Question_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Questionnaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Questionnaire</description>
        <label>Questionnaire</label>
        <referenceTo>Questionnaire__c</referenceTo>
        <relationshipLabel>Question_Questionnaires</relationshipLabel>
        <relationshipName>Question_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question Questionnaire</label>
    <nameField>
        <label>Question Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question_Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Questionnaire__c.object
<CustomObject>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AppSetupController.cls
public with sharing class AppSetupController {
	
	@AuraEnabled
	public static String getTemplates() {
		String query='Select Id,Name from Questionnaire__c ORDER BY Name ASC';
		List<sObject> objList = FBUtils.getRecords('Questionnaire__c', 'Id,Name', query);
        return JSON.serialize(objList);
	}

	@AuraEnabled
	public static String getSections(String qid) {
		System.debug('qid::::'+qid);
        String results = '[]';
        if(FBUtils.isSafeField('GKN_FB__Question_Questionnaire__c','Question_Group__c',true,false,false,false) && 
        	FBUtils.isSafeField('GKN_FB__Question_Group__c','Name',true,false,false,false))
        {
        	AggregateResult [] res = [Select count(id),Question_Group__c,MIN(Question_Group__r.Name) sectionName from Question_Questionnaire__c WHERE Questionnaire__c=:qid group by Question_Group__c];
    		results = JSON.serialize(res);
		}
		return results;
	}
}