src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Is_Allow_Branching__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Admin can set question branches</description>
        <label>Is Allow Branching</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_To_Column__c</fullName>
        <description>Define which question is related to particular column.</description>
        <inlineHelpText>Define which question is related to particular column.</inlineHelpText>
        <label>Related To Column</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked when question deleted .</description>
        <inlineHelpText>Checked when question deleted .</inlineHelpText>
        <label>is Delete</label>
        <type>Checkbox</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Group__c.object
<CustomObject>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>Set Question Group order</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>is_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked when section will be deleted by admin.</description>
        <inlineHelpText>Checked when section will be deleted by admin.</inlineHelpText>
        <label>is Delete</label>
        <type>Checkbox</type>
    </fields>
    <label>Question Group</label>
    <nameField>
        <label>Question Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Option__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Set value for question option</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Options</relationshipLabel>
        <relationshipName>Question_Options</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Question Option</label>
    <nameField>
        <label>Question Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>Is_Allow_Branching__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Admin can allowing  branches for  question</description>
        <label>Is Allow Branching</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Question Group</description>
        <label>Question Group</label>
        <referenceTo>Question_Group__c</referenceTo>
        <relationshipLabel>Question_Questionnaires</relationshipLabel>
        <relationshipName>Question_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Order__c</fullName>
        <description>Set order of the question</description>
        <label>Question Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question_Questionnaires</relationshipLabel>
        <relationshipName>Question_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Questionnaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Questionnaire</description>
        <label>Questionnaire</label>
        <referenceTo>Questionnaire__c</referenceTo>
        <relationshipLabel>Question_Questionnaires</relationshipLabel>
        <relationshipName>Question_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_To_Column__c</fullName>
        <description>Define which question is related to particular column.</description>
        <inlineHelpText>Define which question is related to particular column.</inlineHelpText>
        <label>Related To Column</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_Delete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox will be checked when Question Questionnaire record  will be deleted.</description>
        <inlineHelpText>Checkbox will be checked when Question Questionnaire record  will be deleted.</inlineHelpText>
        <label>is Delete</label>
        <type>Checkbox</type>
    </fields>
    <label>Question Questionnaire</label>
    <nameField>
        <label>Question Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question_Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Questionnaire__c.object
<CustomObject>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Questionnaire_Dynamic_Logic__c.object
<CustomObject>
    <fields>
        <fullName>Question_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Question Group</description>
        <label>Question Group</label>
        <referenceTo>Question_Group__c</referenceTo>
        <relationshipLabel>Questionnaire Dynamic Logic</relationshipLabel>
        <relationshipName>Dynamic_Logic</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Option__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Question Option</description>
        <label>Question Option</label>
        <referenceTo>Question_Option__c</referenceTo>
        <relationshipLabel>Questionnaire Dynamic Logic</relationshipLabel>
        <relationshipName>Dynamic_Logic</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Questionnaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Question Questionnaire</description>
        <label>Question Questionnaire</label>
        <referenceTo>Question_Questionnaire__c</referenceTo>
        <relationshipLabel>Questionnaire Dynamic Logic (Question Questionnaire)</relationshipLabel>
        <relationshipName>Dynamic_Logic</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show_Question_Questionnaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Question Questionnaire</description>
        <label>Show Question Questionnaire</label>
        <referenceTo>Question_Questionnaire__c</referenceTo>
        <relationshipLabel>Questionnaire Dynamic Logic (Show Question Questionnaire)</relationshipLabel>
        <relationshipName>Dynamic_Logic1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Questionnaire Dynamic Logic</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Dynamic Logic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaire Dynamic Logic</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddQuestionInSectionCtr.cls
public class AddQuestionInSectionCtr{
    @AuraEnabled 
    public static boolean saveQstnInSection(String qquaireId,String selectedSectionId,String targetCol){
        boolean isUpdated=false;
        if(String.isNotBlank(qquaireId) && String.isNotBlank(selectedSectionId)){
            Question_Questionnaire__c qstnQuaire=[Select Id,Question__c, Question_Group__c,Is_Allow_Branching__c,Question_Order__c From Question_Questionnaire__c Where Id=:qquaireId];
            // When no question branching is available
            if(qstnQuaire!=null){
                Integer order=[Select count() from Question_Questionnaire__c where Question_Group__c=:selectedSectionId];
                if(qstnQuaire.Is_Allow_Branching__c==false){
                    if(qstnQuaire.Question_Group__c==selectedSectionId){
                        isUpdated=false;
                    }
                    else{
                        qstnQuaire.Related_To_Column__c=targetCol;
                        qstnQuaire.Question_Group__c=selectedSectionId;
                        qstnQuaire.Question_Order__c=order+1;
                        update qstnQuaire;

                        Question__c ques = new Question__c();
                        ques.Id = qstnQuaire.Question__c;
                        ques.Related_To_Column__c = targetCol;
                        update ques;
                        isUpdated=true;
                    }
                }
                else{
                    // When question branching is available
                    if(qstnQuaire.Question_Group__c==selectedSectionId){
                        isUpdated=false;
                    }
                    else{

                        List<String> questionIdList = new List<string>();
                        List<Question__c> questionToUpdate = new List<Question__c>();

                        List<String> lstChildQstnQuariIds=new List<String>();
                        List<Questionnaire_Dynamic_Logic__c> lstQuestnnaireDynLogic = [Select Id,Question_Questionnaire__c,Question_Group__c,Question_Option__c,Show_Question_Questionnaire__c from
                        Questionnaire_Dynamic_Logic__c where Question_Questionnaire__c =:qquaireId];
                        for(Questionnaire_Dynamic_Logic__c qstnDynlgc:lstQuestnnaireDynLogic){
                            qstnDynlgc.Question_Group__c=selectedSectionId;
                            lstChildQstnQuariIds.add(qstnDynlgc.Show_Question_Questionnaire__c);
                        }
                        if(lstChildQstnQuariIds!=null && lstChildQstnQuariIds.size()>0){
                            List<Question_Questionnaire__c> lstQstnQuaire=[Select Id,Question__c,Question_Group__c,Is_Allow_Branching__c,Question_Order__c From Question_Questionnaire__c
                            Where Id IN:lstChildQstnQuariIds];
                            Integer i=2;
                            for(Question_Questionnaire__c childQstnQuaire:lstQstnQuaire){
                                childQstnQuaire.Question_Group__c=selectedSectionId;
                                childQstnQuaire.Question_Order__c=order+i;
                                i=i+1;
                                questionIdList.add(childQstnQuaire.Question__c);
                            }
                            qstnQuaire.Related_To_Column__c=targetCol;
                            qstnQuaire.Question_Group__c=selectedSectionId;
                            update lstQuestnnaireDynLogic;
                            // Update order in parent
                            qstnQuaire.Question_Order__c=order+1;
                            update qstnQuaire;

                            Question__c ques2 = new Question__c();
                            ques2.Id = qstnQuaire.Question__c;
                            ques2.Related_To_Column__c = targetCol;
                            update ques2;

                            for(String id : questionIdList)
                            {
                                Question__c ques = new Question__c();
                                ques.Id = id;
                                ques.Related_To_Column__c = targetCol;
                                questionToUpdate.add(ques);
                            }
                            update questionToUpdate;


                            // Update question order in childs 
                            update lstQstnQuaire;
                            isUpdated=true;
                        }
                    }
                 }
            }
        }
        return isUpdated;
    }
    
    @AuraEnabled 
    public static List<Question_Group__c> getQuestionGroups(String qnaireId){
        List<String> lstQstnGrpIds=new List<String>();
        List<Question_Questionnaire__c> lstQQ=[select id,Questionnaire__c,Question_Group__c from Question_Questionnaire__c where Questionnaire__c=:qnaireId and is_delete__c=false];
        for(Question_Questionnaire__c qq:lstQQ){
            lstQstnGrpIds.add(qq.Question_Group__c);
        }
        List<Question_Group__c> lstQsthGroup=[Select Id,Name,Sort_Order__c From Question_Group__c Where Id IN:lstQstnGrpIds order by Sort_Order__c asc];
        return lstQsthGroup;
    }
    
    @AuraEnabled 
    public static List<Question_Group__c> updateQuestionGroupsSortingOrder(List<Question_Group__c> lstUpdatedQstnGrp){
        update lstUpdatedQstnGrp;
        return lstUpdatedQstnGrp;
    }
}