src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Attachments__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For check, Allow for Attachments</description>
        <inlineHelpText>For check, Allow for Attachments</inlineHelpText>
        <label>Allow_Attachments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Comment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Admin allows to user add a comment on the question.</description>
        <label>Allow Comment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>select Question Category type</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FB_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Help_Text_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allow admin to enter help text of question when checkbox checked.</description>
        <label>Help Text Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <description>Question Help Text</description>
        <label>Help Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>Question label</description>
        <label>Question Label</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Library__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Question Library</description>
        <label>Question Library</label>
        <referenceTo>Question_Library__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For check, question is required or not.</description>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Set a Question Type</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TextPlain</fullName>
                </value>
                <value>
                    <fullName>RichText</fullName>
                </value>
                <value>
                    <fullName>Address</fullName>
                </value>
                <value>
                    <fullName>GPSLocate</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
                <value>
                    <fullName>MultiSelect</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Switch</fullName>
                </value>
                <value>
                    <fullName>Slider</fullName>
                </value>
                <value>
                    <fullName>GPS Location</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Radio</fullName>
                </value>
                <value>
                    <fullName>Header/Footer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Group__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>Set Question score</description>
        <label>Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Question Group</label>
    <nameField>
        <label>Question Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Library__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Question library Description</description>
        <inlineHelpText>Question library Description</inlineHelpText>
        <label>Description</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Question library name</description>
        <inlineHelpText>Question library name</inlineHelpText>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Question Library</label>
    <nameField>
        <label>Question Lib Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Option__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <description>Lookup with Question</description>
        <label>Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Set value for question option</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Options</relationshipLabel>
        <relationshipName>Question_Options</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>Define the score of question option.</description>
        <inlineHelpText>Define the score of question option.</inlineHelpText>
        <label>Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Question Option</label>
    <nameField>
        <label>Question Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Attachments__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allow user to upload attachment.</description>
        <inlineHelpText>Allow user to upload attachment.</inlineHelpText>
        <label>Allow_Attachments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Comment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allow user to put comment.</description>
        <inlineHelpText>Allow user to put comment.</inlineHelpText>
        <label>Allow Comment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Set Question Questionnaire Category</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FB_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Help_Text_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allow admin to enter help text of question when checkbox checked.</description>
        <inlineHelpText>Allow admin to enter help text of question when checkbox checked.</inlineHelpText>
        <label>Help Text Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <description>Show the help text of questions.</description>
        <inlineHelpText>Show the help text of questions.</inlineHelpText>
        <label>Help Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Question Group</description>
        <label>Question Group</label>
        <referenceTo>Question_Group__c</referenceTo>
        <relationshipLabel>Question_Questionnaires</relationshipLabel>
        <relationshipName>Question_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Order__c</fullName>
        <description>Set order of the question</description>
        <label>Question Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question_Questionnaires</relationshipLabel>
        <relationshipName>Question_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Questionnaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Questionnaire</description>
        <label>Questionnaire</label>
        <referenceTo>Questionnaire__c</referenceTo>
        <relationshipLabel>Question_Questionnaires</relationshipLabel>
        <relationshipName>Question_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set true/false for question is required or not</description>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Question Questionnaire</label>
    <nameField>
        <label>Question Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question_Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>Set questionnaire category type</description>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FB_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Community_URL__c</fullName>
        <label>Community URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Questionnaire information</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Questionnaire_Dynamic_Logic__c.object
<CustomObject>
    <fields>
        <fullName>Question_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Question Group</description>
        <label>Question Group</label>
        <referenceTo>Question_Group__c</referenceTo>
        <relationshipLabel>Questionnaire Dynamic Logic</relationshipLabel>
        <relationshipName>Dynamic_Logic</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Option__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Question Option</description>
        <label>Question Option</label>
        <referenceTo>Question_Option__c</referenceTo>
        <relationshipLabel>Questionnaire Dynamic Logic</relationshipLabel>
        <relationshipName>Dynamic_Logic</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Questionnaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Question Questionnaire</description>
        <label>Question Questionnaire</label>
        <referenceTo>Question_Questionnaire__c</referenceTo>
        <relationshipLabel>Questionnaire Dynamic Logic (Question Questionnaire)</relationshipLabel>
        <relationshipName>Dynamic_Logic</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Questionnaire Dynamic Logic</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Dynamic Logic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaire Dynamic Logic</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/FB_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Safety</fullName>
    </customValue>
    <customValue>
        <fullName>Girikon</fullName>
    </customValue>
    <description>Create FB category global picklist</description>
    <masterLabel>FB Category</masterLabel>
</GlobalValueSet>

src/classes/CreateTemplateCtrl_Test.cls
@isTest
public class CreateTemplateCtrl_Test {
    static testMethod void createQniareRecordTestMethod(){
        //Create Question Library
        Question_Library__c oQL= new Question_Library__c(Name='Global Default',Name__c='Global Default');
        insert oQL;

        //Create Question Record 
        Question__c oQue = new Question__c(Name='Test',Help_Text_Required__c=true, Name__c='Test 1', Help_Text__c='Test Help Text', Label__c='Question 1', 
            Question_Library__c=oQL.id, Required__c=true, Type__c='TextPlain',Allow_Comment__c=true,Allow_Attachments__c=true);
        insert oQue;
        List<Question__c> lstQutn = [Select id,Type__c from Question__c where id=:oQue.id];
        System.assertEquals(oQue.Type__c,lstQutn[0].Type__c);
        //create Question option record.
        Question_Option__c qOption = new Question_Option__c(Name ='Test',Name__c='test',Score__c=1,Question__c=oQue.id);
        insert qOption; 
		List<Question_Option__c> lstqOption = [Select id,Score__c from Question_Option__c where Question__c=:oQue.id];
        System.assertNotEquals(lstqOption, null);
        System.assertEquals(qOption.Score__c,lstqOption[0].Score__c);
        
        Question__c oQue2 = new Question__c(Name='Test', Name__c='Test 1', Help_Text__c='Test Help Text', Label__c='Question 1', 
            Question_Library__c=oQL.id, Required__c=true, Type__c='TextPlain',Allow_Comment__c=true,Allow_Attachments__c=true,Help_Text_Required__c=true);

        //Create Questionnaire record
        Questionnaire__c oQnaire = new Questionnaire__c();
        oQnaire.Name='Template 1';
        oQnaire.Category__c='Healthcare';
        oQnaire.Description__c='Template 1';
        oQnaire.Community_URL__c=URL.getSalesforceBaseUrl().toExternalForm();
        insert oQnaire;
        List<Questionnaire__c> lstQuQnaire = [Select id,Category__c from Questionnaire__c where id=:oQnaire.id];
        System.assertEquals(oQnaire.Category__c,lstQuQnaire[0].Category__c);

        //Create Question Group record
        
        Question_Group__c oQG = new Question_Group__c(Name='Test Group');
        insert oQG;
        List<Question_Group__c> lstQuGroup = [Select id,Name from Question_Group__c where id=:oQG.id];
        System.assertEquals(oQG.Name,lstQuGroup[0].Name);

        //Create Question Questionnaire Record
        Question_Questionnaire__c oQQuesnaire= new Question_Questionnaire__c(Allow_Attachments__c=oQue.Allow_Attachments__c,Allow_Comment__c=oQue.Allow_Comment__c,
            Questionnaire__c = oQnaire.id,Name=oQnaire.Name,Question_Group__c =oQG.id,Question__c=oQue.id,Question_Order__c=1);
        insert oQQuesnaire;

        List<Question_Questionnaire__c> lstQuestionQnnaire = [Select id,Question__c from Question_Questionnaire__c where id=:oQQuesnaire.id];
        System.assertEquals(oQQuesnaire.Question__c,lstQuestionQnnaire[0].Question__c);
        
        Test.startTest();
            List<String> lstCategoris = CreateTemplateCtrl.getQueCategory();
            System.assert(lstCategoris.size()>0,'exist Categories');

            Question__c questn = CreateTemplateCtrl.getQuesDetail(oQue.id);
            System.assertEquals(questn.id,oQue.id);

            String sDefaultLib = CreateTemplateCtrl.getDefaultQuestnLibraryId();
            System.assert(sDefaultLib != null,'exist Default Library Id');
            List<Question_Library__c> lstQuestnLib = [Select id from Question_Library__c where Name='Global Default'];
            System.assert(lstQuestnLib != null,'exist Default Library');
            System.assertEquals(lstQuestnLib[0].id,sDefaultLib);

            CreateTemplateCtrl.saveEditQuesRecord(oQue);
            List<Question__c> lstQuestion = [Select id,Allow_Comment__c from Question__c where id=: oQue.id];
            System.assertNotEquals(lstQuestion,null);
            System.assertEquals(lstQuestion[0].Allow_Comment__c,true);

            QuestionGroupWithQuestionsWrap questnWrap = CreateTemplateCtrl.getQuestnsForQuesGroup(oQnaire.id,oQG.id);
            System.assertNotEquals(questnWrap,null);
            Integer countQuestnQnaireResult = [Select count() from Question_Questionnaire__c where Questionnaire__c =:oQnaire.id and Question_Group__c=:oQG.id];
            System.assertNotEquals(countQuestnQnaireResult,null);
            System.assertEquals(questnWrap.lstQuestn.size(),countQuestnQnaireResult);

            String templateName = CreateTemplateCtrl.getTemplateName(oQnaire.id);
            System.assertNotEquals(templateName,null);

            String questionnaireName = [Select Name from Questionnaire__c where id=:oQnaire.id].Name;
            System.assertNotEquals(questionnaireName,null);
            System.assertEquals(questionnaireName,templateName);

            List<Question_Questionnaire__c> lstQuesQnaire = CreateTemplateCtrl.getAllQuestnGrpNameForQuesnnaire(oQnaire.id);
            System.assertNotEquals(lstQuesQnaire,null);
            Integer countQutnQnaireResult = [Select count() from Question_Questionnaire__c where Questionnaire__c=:oQnaire.id and Question__c = null];
            System.assertNotEquals(countQutnQnaireResult,null);
            System.assertEquals(lstQuesQnaire.size(),countQutnQnaireResult); 

            CreateTemplateCtrl.createQuestnAndQuestnQnaire(oQnaire.id,oQG.id,oQue2,oQnaire.Name,'1','col1');
            List<Question_Questionnaire__c> lstQuesQnaireResult = [Select id from Question_Questionnaire__c where Questionnaire__c=:oQnaire.id 
            and Question_Group__c =: oQG.id ]; 
            System.assertNotEquals(lstQuesQnaireResult,null);
            System.assertNotEquals(lstQuesQnaireResult.size(),0);
            
            CreateTemplateCtrl.delQuestion(oQQuesnaire.id);
            List<Question_Questionnaire__c> lstQuesQuestnnaireResult = [Select id from Question_Questionnaire__c where id=:oQQuesnaire.id and is_delete__c =true];
            System.assertNotEquals(lstQuesQuestnnaireResult,null);
            System.assertEquals(lstQuesQuestnnaireResult.size(),1);

            CreateTemplateCtrl.createSection('Test Group1',oQnaire.id,'4');
            String groupName = [Select Name from Question_Group__c where Name='Test Group1'].Name ;
            System.assertNotEquals(groupName,null);
            System.assertEquals(groupName,'Test Group1');
        
            Questionnaire__c questnRueslt= CreateTemplateCtrl.getTemplateRecord(oQnaire.id);
            System.assertNotEquals(questnRueslt,null);
            System.assertEquals(questnRueslt.Name,'Template 1');
        
            List<Question_Option__c> lstScoreAndWeight = CreateTemplateCtrl.getScoreAndWeight(oQue.id);
        	System.assertNotEquals(lstScoreAndWeight, null);
        	CreateTemplateCtrl.setpublishStatusOnTemplate(oQnaire.id);
        	List<Questionnaire__c> lstQuQnaireResult = [Select id,Category__c from Questionnaire__c where id=:oQnaire.id and is_Published__c =true];
        	System.assertNotEquals(lstQuQnaireResult, null);
        	CreateTemplateCtrl.deleteSectionWithQuestionsAndQstnQustnry(oQG.id,oQnaire.id);
            List<Question_Group__c> lstQuestnGroup =[Select id,is_Delete__c from Question_Group__c where id=:oQG.id ];
            System.assertNotEquals(lstQuestnGroup,null);
            System.assertEquals(lstQuestnGroup[0].is_Delete__c,true);
        Test.stopTest();
    }
    
    static testMethod void createBranchingRecordTestMethod(){
        //Create Question Library
        Question_Library__c oQL= new Question_Library__c(Name='Global Default',Name__c='Global Default');
        insert oQL;

        //Create Question Record 
        Question__c oQue = new Question__c(Name='Test',Help_Text_Required__c=true, Name__c='Test 1', Help_Text__c='Test Help Text', Label__c='Question 1', 
            Question_Library__c=oQL.id, Required__c=true, Type__c='TextPlain',Allow_Comment__c=true,Allow_Attachments__c=true);
        insert oQue;
        List<Question__c> lstQutn = [Select id,Type__c from Question__c where id=:oQue.id];
        System.assertEquals(oQue.Type__c,lstQutn[0].Type__c);
        //create Question Option
        Question_Option__c qOption = new Question_Option__c(Name ='Option 1',Name__c='Option 1',Question__c =oQue.id);
        insert qOption;
        List<Question_Option__c> listQueOptionData  = [Select id,Name__c from Question_Option__c];
        System.assertNotEquals(listQueOptionData,null);
        System.assertEquals(listQueOptionData.size(),1);
        //Create Questionnaire record
        Questionnaire__c oQnaire = new Questionnaire__c();
        oQnaire.Name='Template 1';
        oQnaire.Category__c='Healthcare';
        oQnaire.Description__c='Template 1';
        oQnaire.Community_URL__c=URL.getSalesforceBaseUrl().toExternalForm();
        insert oQnaire;
        List<Questionnaire__c> lstQuQnaire = [Select id,Category__c from Questionnaire__c where id=:oQnaire.id];
        System.assertEquals(oQnaire.Category__c,lstQuQnaire[0].Category__c);

        //Create Question Group record
        
        Question_Group__c oQG = new Question_Group__c(Name='Test Group');
        insert oQG;
        List<Question_Group__c> lstQuGroup = [Select id,Name from Question_Group__c where id=:oQG.id];
        System.assertEquals(oQG.Name,lstQuGroup[0].Name);

        //Create Question Questionnaire Record
        List<Question_Questionnaire__c> lstQuestionQnnaireAdd = new List<Question_Questionnaire__c>();
        Question_Questionnaire__c oQQuesnaireMain= new Question_Questionnaire__c(Allow_Attachments__c=oQue.Allow_Attachments__c,Allow_Comment__c=oQue.Allow_Comment__c,
            Questionnaire__c = oQnaire.id,Name=oQnaire.Name,Question_Group__c =oQG.id,Question__c=oQue.id,Question_Order__c=1);
        lstQuestionQnnaireAdd.add(oQQuesnaireMain);

        Question_Questionnaire__c oQQuesnaireBranching= new Question_Questionnaire__c(Allow_Attachments__c=oQue.Allow_Attachments__c,Allow_Comment__c=oQue.Allow_Comment__c,
            Questionnaire__c = oQnaire.id,Name=oQnaire.Name,Question_Group__c =oQG.id,Question__c=oQue.id,Question_Order__c=2);
        lstQuestionQnnaireAdd.add(oQQuesnaireBranching);
        Question_Questionnaire__c oQQuesnaireBranchingSecond= new Question_Questionnaire__c(Allow_Attachments__c=oQue.Allow_Attachments__c,Allow_Comment__c=oQue.Allow_Comment__c,
            Questionnaire__c = oQnaire.id,Name=oQnaire.Name,Question_Group__c =oQG.id,Question__c=oQue.id,Question_Order__c=2);
        lstQuestionQnnaireAdd.add(oQQuesnaireBranchingSecond);
        insert lstQuestionQnnaireAdd;
        System.assertNotEquals(lstQuestionQnnaireAdd,null);
        List<Question_Questionnaire__c> lstQuestionQnnaire = [Select id,Question__c from Question_Questionnaire__c where id=:lstQuestionQnnaireAdd[0].id];
        System.assertEquals(lstQuestionQnnaireAdd[0].Question__c,lstQuestionQnnaire[0].Question__c);
        
        //create Questionnaire_Dynamic_Logic record
        Questionnaire_Dynamic_Logic__c QuestnDynLogic = new Questionnaire_Dynamic_Logic__c(Question_Questionnaire__c=lstQuestionQnnaireAdd[0].id,Question_Group__c =oQG.id,Question_Option__c=qOption.id,Show_Question_Questionnaire__c=lstQuestionQnnaireAdd[1].id);
        insert QuestnDynLogic;
        // for insert data
        Questionnaire_Dynamic_Logic__c QuestnDynLogicInsert = new Questionnaire_Dynamic_Logic__c(Question_Questionnaire__c=lstQuestionQnnaireAdd[0].id,Question_Group__c =oQG.id,Question_Option__c=qOption.id,Show_Question_Questionnaire__c=lstQuestionQnnaireAdd[1].id);
        List<Questionnaire_Dynamic_Logic__c> lstQDLData = new List<Questionnaire_Dynamic_Logic__c>();
        lstQDLData.add(QuestnDynLogicInsert);
        System.assertNotEquals(lstQDLData,null);
        List<Questionnaire_Dynamic_Logic__c> lstQDLogic = [Select id from Questionnaire_Dynamic_Logic__c where Question_Questionnaire__c=:lstQuestionQnnaireAdd[0].id and Question_Group__c =:oQG.id and Question_Option__c=:qOption.id];
        System.assertNotEquals(lstQDLogic,null);
        System.assertEquals(lstQDLogic.size(),1);
        Test.startTest();
            List<Questionnaire_Dynamic_Logic__c> lstBranchingQuestn = CreateTemplateCtrl.getBranchingQuestn(oQG.id);
            System.assertNotEquals(lstBranchingQuestn, null);
            System.assertEquals(lstBranchingQuestn.size(),1);
            for(Question_Questionnaire__c obj : lstQuestionQnnaireAdd){
                obj.question_order__c = 1;
            }
        	CreateTemplateCtrl.setQuestnQnniareOrder(lstQuestionQnnaireAdd);
        	System.assertNotEquals(lstQuestionQnnaireAdd, null);
        	System.assertEquals(lstQuestionQnnaireAdd[0].question_order__c, 1);
        Test.stopTest();
    }
}