src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Attachments__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For check, Allow for Attachments</description>
        <inlineHelpText>For check, Allow for Attachments</inlineHelpText>
        <label>Allow_Attachments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Comment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Admin allows to user add a comment on the question.</description>
        <label>Allow Comment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Currency__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Admin can define whether its number or a currency, in case of currency, user should be able to choose the currency symbol.</description>
        <label>Allow Currency</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>select Question Category type</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FB_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Currency_Symbol__c</fullName>
        <description>Admin can set currency on Question</description>
        <label>Currency Symbol</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Currency_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Decimal_value__c</fullName>
        <label>Decimal value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Help_Text_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allow admin to enter help text of question when checkbox checked.</description>
        <label>Help Text Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <description>Question Help Text</description>
        <label>Help Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Allow_Branching__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Admin can set question branches</description>
        <label>Is Allow Branching</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>Question label</description>
        <label>Question Label</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Max_Char_Length__c</fullName>
        <description>Admin can specify the max char length of the text associated with that question in a questionnaire.</description>
        <label>Max Char Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Library__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Question Library</description>
        <label>Question Library</label>
        <referenceTo>Question_Library__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_To_Column__c</fullName>
        <description>Define which question is related to particular column.</description>
        <inlineHelpText>Define which question is related to particular column.</inlineHelpText>
        <label>Related To Column</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For check, question is required or not.</description>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Define the weight of question.</description>
        <inlineHelpText>Define the weight of question.</inlineHelpText>
        <label>Weight</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Group__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>Set Question score</description>
        <label>Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Question Group</label>
    <nameField>
        <label>Question Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Library__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <description>Question library name</description>
        <inlineHelpText>Question library name</inlineHelpText>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Question Library</label>
    <nameField>
        <label>Question Lib Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Option__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <description>Lookup with Question</description>
        <label>Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Set value for question option</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Options</relationshipLabel>
        <relationshipName>Question_Options</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>Define the score of question option.</description>
        <inlineHelpText>Define the score of question option.</inlineHelpText>
        <label>Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Set value for question option</description>
        <label>Value</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <description>Set weight for Question option</description>
        <label>Weight</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Question Option</label>
    <nameField>
        <label>Question Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Attachments__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allow user to upload attachment.</description>
        <inlineHelpText>Allow user to upload attachment.</inlineHelpText>
        <label>Allow_Attachments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Comment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allow user to put comment.</description>
        <inlineHelpText>Allow user to put comment.</inlineHelpText>
        <label>Allow Comment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Currency__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Admin can define whether its number or a currency, in case of currency, user should be able to choose the currency symbol.</description>
        <label>Allow Currency</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Set Question Questionnaire Category</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FB_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Currency_Symbol__c</fullName>
        <label>Currency Symbol</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Currency_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Decimal_value__c</fullName>
        <description>Admin can define the number of the decimal to be allowed</description>
        <label>Decimal value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Help_Text_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allow admin to enter help text of question when checkbox checked.</description>
        <inlineHelpText>Allow admin to enter help text of question when checkbox checked.</inlineHelpText>
        <label>Help Text Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <description>Show the help text of questions.</description>
        <inlineHelpText>Show the help text of questions.</inlineHelpText>
        <label>Help Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Allow_Branching__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Admin can allowing  branches for  question</description>
        <label>Is Allow Branching</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Char_Length__c</fullName>
        <label>Max Char Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Question Group</description>
        <label>Question Group</label>
        <referenceTo>Question_Group__c</referenceTo>
        <relationshipLabel>Question_Questionnaires</relationshipLabel>
        <relationshipName>Question_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Order__c</fullName>
        <description>Set order of the question</description>
        <label>Question Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question_Questionnaires</relationshipLabel>
        <relationshipName>Question_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Questionnaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup with Questionnaire</description>
        <label>Questionnaire</label>
        <referenceTo>Questionnaire__c</referenceTo>
        <relationshipLabel>Question_Questionnaires</relationshipLabel>
        <relationshipName>Question_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_To_Column__c</fullName>
        <description>Define which question is related to particular column.</description>
        <inlineHelpText>Define which question is related to particular column.</inlineHelpText>
        <label>Related To Column</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set true/false for question is required or not</description>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Define the weight of question.</description>
        <inlineHelpText>Define the weight of question.</inlineHelpText>
        <label>Weight</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Question Questionnaire</label>
    <nameField>
        <label>Question Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question_Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>Set questionnaire category type</description>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FB_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Currency_Code.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>$</fullName>
    </customValue>
    <customValue>
        <fullName>¥</fullName>
    </customValue>
    <customValue>
        <fullName>€</fullName>
    </customValue>
    <customValue>
        <fullName>£</fullName>
    </customValue>
    <customValue>
        <fullName>ƒ</fullName>
    </customValue>
    <customValue>
        <fullName>P</fullName>
    </customValue>
    <customValue>
        <fullName>¢</fullName>
    </customValue>
    <customValue>
        <fullName>Q</fullName>
    </customValue>
    <customValue>
        <fullName>L</fullName>
    </customValue>
    <customValue>
        <fullName>kr</fullName>
    </customValue>
    <customValue>
        <fullName>p.</fullName>
    </customValue>
    <customValue>
        <fullName>R$</fullName>
    </customValue>
    <customValue>
        <fullName>Ft</fullName>
    </customValue>
    <customValue>
        <fullName>Rp</fullName>
    </customValue>
    <customValue>
        <fullName>J$</fullName>
    </customValue>
    <customValue>
        <fullName>Lt</fullName>
    </customValue>
    <customValue>
        <fullName>C$</fullName>
    </customValue>
    <customValue>
        <fullName>$U</fullName>
    </customValue>
    <customValue>
        <fullName>Z$</fullName>
    </customValue>
    <customValue>
        <fullName>TT$</fullName>
    </customValue>
    <customValue>
        <fullName>R</fullName>
    </customValue>
    <description>Setting currency code values</description>
    <masterLabel>Currency Code</masterLabel>
</GlobalValueSet>

src/globalValueSets/FB_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Safety</fullName>
    </customValue>
    <customValue>
        <fullName>Girikon</fullName>
    </customValue>
    <description>Create FB category global picklist</description>
    <masterLabel>FB Category</masterLabel>
</GlobalValueSet>

src/classes/CheckboxInputCtr.cls
public class CheckboxInputCtr{
     /**
     * Create question and question questionnaire.
     * @param  qnaireId: Questionnaire id.
     * @param  qGroupId: Question group id.
     * @param  question: Question object values.
     * @param  qnaireName : Questionnaire name.
     * @param  qOrder: Order of question.
     * @param  colNumber: column number of question.
     * @param  questnOptns: Question options of the question.
     */
    @AuraEnabled 
    public static void createQuestnAndQuestnQnaireWithOptions(String qnaireId,String qGroupId,Question__c question,String qnaireName,String qOrder,String colNumber,String questnOptns){
        String sQLib = CreateTemplateCtrl.getDefaultQuestnLibraryId();
        question.Name__c = question.Label__c;
        question.Related_To_Column__c = colNumber;
        if(String.isNotBlank( sQLib)){
            question.Question_Library__c = sQLib; 
        }
        qOrder = String.valueOf(FieldInputCtr.countQuestnQuestnnaireRecord(qnaireId, qGroupId));
        question.Name = qOrder;
        insert question;
        Question_Questionnaire__c oQQuesnaire= new Question_Questionnaire__c(Weight__c=question.Weight__c,Required__c=question.Required__c,
            Allow_Currency__c =question.Allow_Currency__c,Decimal_value__c =question.Decimal_value__c,
            Related_To_Column__c=colNumber,Help_Text__c=question.Help_Text__c,Help_Text_Required__c=question.Help_Text_Required__c,
            Category__c=question.Category__c,Allow_Attachments__c=question.Allow_Attachments__c,Allow_Comment__c=question.Allow_Comment__c,
            Questionnaire__c = qnaireId,Name=qnaireName,Question_Group__c =qGroupId,Question__c=question.id,Question_Order__c=Integer.valueOf(qOrder),Is_Allow_Branching__c =question.Is_Allow_Branching__c);
        oQQuesnaire.Max_Char_Length__c=(question.Max_Char_Length__c != null?question.Max_Char_Length__c:0);
        if(String.isNotBlank(question.Currency_Symbol__c)){
            oQQuesnaire.Currency_Symbol__c=question.Currency_Symbol__c;
        }
        
        insert oQQuesnaire;
        List<fieldWrapper> qstnOptnList = (List<fieldWrapper>) JSON.deserialize(questnOptns, List<fieldWrapper>.class);
        List<Question_Option__c> lstQstnOptn=new List<Question_Option__c>();
        Question_Option__c qusthOption;
        for(fieldWrapper wrapper: qstnOptnList){
            qusthOption=new Question_Option__c();
            qusthOption.Name = wrapper.name;
            qusthOption.Name__c = wrapper.name;
            qusthOption.Question__c = question.id;
            if(String.isNotBlank(wrapper.score)){
                qusthOption.Score__c = Decimal.ValueOf(wrapper.score);
            }
            
            qusthOption.Value__c = wrapper.alias;
            lstQstnOptn.add(qusthOption);
        }
        insert lstQstnOptn;
    }
    
    /**
     * Save question option  when edit question.
     * @param  oQues: Question object.
     * @param  name: Name of question option.
     * @param  alias: Alias of question option.
     * @param  score: Score of question option.
     * @return : Question record
     */
    @AuraEnabled
    public static Question__c saveQuestionEditOption(Question__c oQues,String name,String alias,String score){
        Question__c question = new Question__c();
        Question_Option__c qusthOption=new Question_Option__c();
        if(oQues != null && String.isNotBlank(name)){
            if(String.isNotBlank(score)){
                qusthOption=new Question_Option__c(Question__c=oQues.id,Name=name,Name__c=name,Score__c=Decimal.ValueOf(score),Value__c=alias);
            }
            else{
                qusthOption=new Question_Option__c(Question__c=oQues.id,Name=name,Name__c=name,Value__c=alias);
            }
            insert qusthOption;
            question = CreateTemplateCtrl.getQuesDetail(oQues.id);
        }
        return question ;
    }
    
     /**
     * Delete question option  when edit question.
     * @param  oQues: Question object
     * @param  qstnOptionId: Id of question option.
     * @return : Question record
     */
    @AuraEnabled
    public static Question__c deleteQuestionOptionInEdit(Question__c oQues,String qstnOptionId){
        Question__c question = new Question__c();
        if(oQues!= null && String.isNotBlank(qstnOptionId)){
           Question_Option__c qstnOption=[Select Id from Question_Option__c Where Id=:qstnOptionId];
           if(qstnOption!=null){
               delete qstnOption;
           }
           question=CreateTemplateCtrl.getQuesDetail(oQues.id);
        }
        return question;
    }
    
    /**
     * Edit question option  when edit question.
     * @param  oQues: Question object
     * @param  qstnOptionId: Id of question option.
     * @return : Question record
     */
    @AuraEnabled
    public static Question__c editQuestionOptionInEdit(Question_Option__c oQuesOption,Question__c oQues){
        Question__c question = new Question__c();
        if(oQuesOption != null && oQues!= null){
           update oQuesOption;
           question=CreateTemplateCtrl.getQuesDetail(oQues.id);
        }
        return question;
    }
    
     /**
     * save edited Question and Question Questionniare record
     * @param  oQues: Question object values.
     * @param  qnaireId: Question object values.
     * @param  sectionId: Question object values.
     */
    @AuraEnabled
    public static void saveEditQuesRecord(Question__c oQues,String qnaireId,String sectionId,Boolean isUnderBranching) {
        if (oQues != null) 
        {
            if(oQues.Help_Text_Required__c==false){
                oQues.Help_Text__c='';

            }
            update oQues;
            
            List<Question_Questionnaire__c> lstQQnnaire=[Select Id,Allow_Attachments__c,Allow_Comment__c,Help_Text_Required__c,Help_Text__c,Category__c from Question_Questionnaire__c where Question__c=:oQues.id and Questionnaire__c=:qnaireId and Question_Group__c=:sectionId];
            if(lstQQnnaire!=null && lstQQnnaire.size()>0)
            {
                lstQQnnaire[0].Allow_Attachments__c=oQues.Allow_Attachments__c;
                lstQQnnaire[0].Allow_Comment__c=oQues.Allow_Comment__c;
                lstQQnnaire[0].Help_Text_Required__c=oQues.Help_Text_Required__c;
                lstQQnnaire[0].Help_Text__c='';
                lstQQnnaire[0].Required__c=oQues.Required__c;
                if(oQues.Help_Text_Required__c==true){
                    lstQQnnaire[0].Help_Text__c=oQues.Help_Text__c;
                }
                lstQQnnaire[0].Is_Allow_Branching__c =oQues.Is_Allow_Branching__c;
                if(lstQQnnaire[0].Is_Allow_Branching__c==false && isUnderBranching ==false){
                    CreateTemplateCtrl.delQuestnDynLogic(lstQQnnaire[0].id);
                }
                if(String.isNotBlank(oQues.Currency_Symbol__c)){
                    lstQQnnaire[0].Currency_Symbol__c=oQues.Currency_Symbol__c;
                }
                lstQQnnaire[0].Decimal_value__c =oQues.Decimal_value__c;
                lstQQnnaire[0].Allow_Currency__c =oQues.Allow_Currency__c;
                lstQQnnaire[0].Max_Char_Length__c =(oQues.Max_Char_Length__c != null?oQues.Max_Char_Length__c:0);
                lstQQnnaire[0].Category__c=oQues.Category__c;
                lstQQnnaire[0].Weight__c=oQues.Weight__c;
                update lstQQnnaire;
            }
        } 
    }


    /**
     * Wrapper class to read quetion option values.
    */
    public with sharing class fieldWrapper {
        public String name;
        public String alias;
        public String score;
    }
}